version: "3"

services:
  webserver:
    build: 
      context: ./bin/webserver
    container_name: 'werkn-apache-webserver'
    restart: 'always'
    ports:
      - "80:80"
      - "443:443"
    links: 
      - mysql
    environment:
      - MYSQL_HOST
      - MYSQL_ROOT_USERNAME
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USERNAME
      - MYSQL_PASSWORD
      - MYSQL_DATABASE  
    volumes: 
      - ${DOCUMENT_ROOT-./www}:/var/www/html
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
  mysql:
    build: ./bin/mysql
    container_name: 'werkn-mysql'
    restart: 'always'
    ports:
      - "3306:3306"
    volumes: 
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER=${MYSQL_USERNAME}
      - MYSQL_PASSWORD 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'werkn-phpmyadmin'
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - '8080:80'
    volumes: 
      - /sessions
